integrations:
  ogbn_arxiv:
    type: dataset
    ref: paperspace/dse7nwrf3tr7cl8:a27q61l
  ogb_lsc_pcqm4mv2:
    type: dataset
    ref: paperspace/dsny3t160bciwgy:yzzo2ta
  poplar-executables-tf2-3-1:
    type: dataset
    ref: paperspace/dswaj6xwmqub6f6:roodlh7
